### 2 深度学习需要掌握的技能

- 数据操作：存储、操作和预处理
- 调整参数需要的微积分知识，autograd包可以自动计算微分
- 机器学习涉及如何做出预测：概率论
- **如何在官方文档中查找所需信息**
- 如需进一步学习数学知识，可以看本书目录

#### 2.1 数据操作

数据操作的过程通常涉及两个部分：

1. 获取数据
1. 将数据读入计算机进行处理。

首先介绍 PyTorch 中的张量，它有两个优势：

1. 支持GPU运算
1. 支持自动微分


##### 2.1.1 入门
基础操作

张量表示一个由数值组成的数组。

具有一个轴的张量对应数学上的向量，具有两个轴的张量对应数学上的矩阵三个轴及以上没有数学名称。

In [2]:
# 导包
import torch

# arange创建一个行向量，包含以0开始的前12个整数
x = torch.arange(12)
x

# 访问shape属性，沿着每个轴的长度的形状
x.shape

torch.Size([12])

In [3]:
# numel()函数检查张量的大小
x.numel()

12

In [4]:
# 只改变形状而不改变张量的元素数量和元素值
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

不需要手动指定每个维度来改变形状，

如果目标形状是（高度，宽度），那么在知道宽度之后，高度就会被自动计算得出，不必自己做除法。

可以使用 `-1` 代替输入高度的位置。

In [5]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

设置全0，全1或者其他张量

或者从特定分布中随机采样来初始矩阵。

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# 从随机分布中采样
torch.randn(3, 4)

tensor([[-0.0890,  1.5584,  0.5688, -0.4210],
        [ 0.0569,  0.9560,  1.2370,  0.4627],
        [-0.1377, -0.1936, -0.8530, -1.5779]])

In [9]:
# 提供包含数值的Python列表，为所需张量的每个元素赋予确定值
# 最外层列表对应轴0，内层列表对应轴1
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

##### 2.1.2 运算符


In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [11]:
# 求幂
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

将多个张量进行链接，端对端地堆叠形成一个更大的张量。

只需提供张量列表，然后给出沿哪个轴连结。

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

torch.cat((X,Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

使用逻辑运算符进行构建二元张量

In [13]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
# 所有元素进行求和，会产生一个单元素张量。

X.sum()

tensor(66.)

##### 2.1.3 广播机制

针对形状不同的张量，使用广播机制来执行按元素操作。

1. 通过适当的复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
1. 对生成的数组执行按元素操作。

在大多数情况下，沿着数组中长度为1的广播。

In [17]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

a是 $3 \times 1$ 矩阵，而b是 $1 \times 2$ 矩阵。

那么，a由1变2，b由1变3。

所以矩阵变成 $3 \times 2$.

In [18]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

##### 2.1.4 索引和切片

第一个元素的索引是 `0`，最后一个元素的索引是 `-1`

还可以指定范围以包含第一个元素和 `最后一个之前` 的元素。

In [19]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
# 通过指定索引将元素写入矩阵
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值的话，那么就索引所有元素，然后进行赋值。


In [21]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

0:2 表示访问第1行和第2行。

: 表示沿轴1的所有元素。